---
- name: restart k3s
  service:
    name: k3s
    state: restarted

- name: stop k3s
  service:
    name: k3s
    state: stopped

- name: start k3s
  service:
    name: k3s
    state: started

- name: reload systemd
  command: systemctl daemon-reload
